workflows:
  ios-workflow:
    name: iOS Build
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          cd /Users/builder/clone/sem-7-AI/personal-project/src/phm_app
          flutter pub get

      - name: Install CocoaPods
        script: |
          cd /Users/builder/clone/sem-7-AI/personal-project/src/phm_app/ios
          pod install

      - name: Build iOS (no codesign)
        script: |
          cd /Users/builder/clone/sem-7-AI/personal-project/src/phm_app
          flutter build ios --release --no-codesign

      - name: Package into unsigned IPA
        script: |
          cd /Users/builder/clone/sem-7-AI/personal-project/src/phm_app/build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/Runner.app
          zip -r Runner.ipa Payload

    artifacts:
      - /Users/builder/clone/sem-7-AI/personal-project/src/phm_app/build/ios/iphoneos/Runner.ipa
      - /tmp/xcodebuild_logs/*.log