[env:esp32_com3]
platform = espressif32
board = esp32dev
framework = arduino
upload_port = COM3
monitor_port = COM3
monitor_speed = 115200
build_flags =
    -D DEVICE_ID=1
    -D DEVICE_NAME=\"ESP32_COM4\"
    -D PLANT_LABEL=\"prayer-plant\"
    -D WIFI_SSID=\"vRijswijk\"
    -D WIFI_PASSWORD='"KvR1964w!%%"'
    -D POF02_ENABLE_TINYML_TFLM=1

lib_deps =
    eloquentarduino/EloquentTinyML
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor

[env:esp32_com4]
platform = espressif32
board = esp32dev
framework = arduino
upload_port = COM5
monitor_port = COM5
monitor_speed = 115200
build_flags =
    -D DEVICE_ID=2
    -D DEVICE_NAME=\"ESP32_COM5\"
    -D PLANT_LABEL=\"Aglaonema\"
    -D WIFI_SSID=\"vRijswijk\"
    -D WIFI_PASSWORD='"KvR1964w!%%"'
    -D POF02_ENABLE_TINYML_TFLM=1

lib_deps =
    eloquentarduino/EloquentTinyML
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
