= Software testing

As mentioned previously, there is made use of multiple types of testing.
Each kind tests a specific aspect of the system. 
The different kinds of testing that are performed, are discussed throughout this chapter.

== Unit Testing (Google test)

For each part of the system there are separate google tests written.
These google tests are written in such a way that it will be easy to figure out the problem when the system unexpectedly breaks.
To optimise the functionality of the tests, they are added to the git and are build during the pipeline. 
If the tests fail, the branch will not be able to merge. 

== Component testing

Certain aspects of the system can not be verified with google tests.
Therefore, component testing is used.
Component testing focuses on one component and its input/output.
When this form of testing is performed, a specific component will be isolated and run through some functional tests.
These functional tests help verify that the component works on its own regarding their main purpose.

== Black box testing

Black box testing is used verify the functionality of the system based on the defined requirements.
There are multiple kind of black box testing, the one that will be used for our purpose are funtional testing.