= System Description

The  system is designed to transform environmental data into musical compositions through the integration of of various components.
The system aims to provide users with an intuitive and engaging experience, offering real-time insights into their environment in the form of unique musical compositions.
As the musical composition has to trigger an emotion based on the current environmental data, therefor, when a value from a sensor is consider poor, the musical composition should be more dark and sinister.
When the environmental data is considered good, the musical composition should be more bright and calming.
Each musical composition will be based upon a different data processing approach.

== Extensions

**Should**

- Generate a musical composition based upon environmental data.
- Collect environmental data.
- Change the data processing approach during run time.
- Store any collected environmental data in a database.

**Could**

- Allow for addition of extra sensors.
