= Communication

As the project is in a work environment, rather than a traditional academic setting, communication is a key aspect of the project.
Rather than having fixed moments for communication, the project is structured around agile sprints, with regular feedback loops and alignment sessions to ensure that the project stays on track and meets the requirements of both the company and the academic institution.
There is more flexibility as the environment is focussed on continuous collaboration and communication, rather than a rigid schedule of meetings and reports.

With the assesor from Fontys there is a set schedule. 
Every other week a meeting will be helped to discuss the process and project status.
Furthermore, this is the moment to discuss any questions.
For any urgent matter, the assesor can be reached via email or teams. 
Regarding to the already defined meeting dates, these are defined in the table <<meeting-schedule-table>>.

[[meeting-schedule-table]]
.Meetings Schedule
|===
| Type of Meeting | Purpose | Occurance | Starting Date
| Assesor | To dicuss the current progress and status. Furthermore, any questions could be asked at this moment. | Bi-weekly | 08-09-2026
| Sprint Demo | To deliver and showcase the booked process form the past sprint. | Every 3 weeks |  04-09-2026
| Peer Show & Tell | To showcase progress with other graduation student from Fontys | week 4, week 9, and week 15 | -
| Table Meeting | To get the current status and booked process, and understand where you are currently standing |  week 4, week 9, and week 15 | -
|===
