= Component Design

== File(s)
- PP-design-component.pdf

== Context and Problem/Opportunity
Following the project context, I needed to design a distributed system, which allows for environmental data to be used by an algorithm to create musical output, and store the collected data. 
The challenge was to create such a design that reflects on my goals and knowledge acquired during my studies.

== Goal and Intended Solution
My aim was to create a component-based design that would demonstrate how the system would be connected trough the different components, while ensuring it would be a distributed system.

== Questions to Be Answered
To plan the design, some questions had to be answered: 
- What components are required for the system? 
- How are the different components connected?
- How will the components communicate with each other?

== Summary of Activities
With the help of brainstorming sessions, an analysis was conducted.
The analysis helped to determine the best approach for designing the system components. 
This led to the creation of a component design, including the relations between components, which is located in the following place <<sprint-1/personal-project/design-component.pdf>>.

== Conclusion and Advises
The component design, which has been created, resonates well with the project's requirements.
This design will guide the implementation phase of the project.