:math:

= Algorithm

== Parallax Feedback 360° High-Speed Servo

=== Speed
The control signal of the servo must be sent every 20ms. To achieve this the reload value of the used timer has to be calculated based on the expected period. 

stem:[ARR = period * clock speed - 1]

stem:[ARR = 0.02s * 16*10^6 - 1 = 320 000 - 1]

The control signal can be manipulated in such a way that the RPM  of the servo can be changed. The RPM helps with finding the minimum and the maximum speed of the servo in cm/s. Since the RPM itself in rad/s, it has to converted into cm/s. To do so, the following calculations have to be made. Since one of the servo's is placed reversed, the speed for this one will be reversed.

stem:[v = RPM / 60  * ( diameter * π)]	 

stem:[v_min = 0 / 60  * ( 7cm * π) = 0 cm/s]	

stem:[v_max = 140 / 60  * ( 7cm * π) = 51,31 cm/s]

To make the servo rotate based on these speeds, the CRR values have to be calculated. This is done with the help of the given tcontrol, the tcontrol is given in microseconds. 
CRR = Duty Cycle * ARR

Clockwise

stem:[CCR_min=  0.00148s / 0.02s  * (320 000 - 1) = 23 680]

stem:[CRR_max=  0.00128s / 0.02s  * (320 000 - 1) = 20 480]


Counter clockwise

stem:[CCR_min=  (1520 * 10^(-3) ms) / 20ms  * (320 000 - 1) = 24 320]

stem:[CRR_max=  (1720 * 10^(-3) ms) / 20ms  * (320 000 - 1) = 27 520]

=== Feedback Control
The timers for the servo's PWM input need be adjusted regarding to its PSC, so it results into an 1,1ms(1MHz) period.
This is done by using the following formula.

stem:[PSC = Timer Frequency / 1 000 000 - 1]

stem:[PSC = 16 000 000 / 1 000 000 - 1 = 16 - 1]


For getting the current duty cycle of a wheel, the retrieved measurement is used to calculate it.
Within this formula, the dutyscale is 1000, unitsFC is 360, dcMin is 29 and dcMax is 971.

stem:[Duty Cycle = (dutyScale * tHigh) / (tHigh + tLow)]


== Ultrasonic sensor : HC-SR04
The duration of the pulse that is being returned to the sensor is measured in microSeconds.
To convert this into the measured distance the following algorithm is applied.
In this formula the time is in microseconds.

stem:[Distance in CM = time * 0.034 / 2 ]