= Part 1 : Trees

== Research
To solve the question of the depth of a tree, there can be made use of two different approaches, Breadth First and Depth First search. 
Breadth first goes down per level, and depth first will go per subtree.
Therefor depth first can be slower when dealing with bigger trees.
Within the header Algorithm there is discussed which of these two options has been chosen.

== Design
=== Tree
To create the tree, there are nodes and its children created.
These nodes are based upon previous assignments, as in they have a similar structure in comparison with for example linked list.
A node has two pointers to a different node, these pointers point to their children.
To insert the node at the correct place in the tree, there is searched in the tree for and child node with the same data as the node that will be created.

=== Algorithm
The used algorithm has been taken from an online source.
The source is : https://www.geeksforgeeks.org/level-order-tree-traversal/ .
This algorithm is based on depth first search. 
Even though depth first is not favorable due to how long it can take to run, for smaller scale it is okay.
Within this algorithm there is searched for the depth of the longest path to the farthest leaf down.

== Reflection
In general the first part went smoothly.
After figuring out how i wanted to create the tree it was an matter of finding a suitable algorithm and implement it.
The biggest struggle i faced throughout this was getting the actual data input.
It took my quite some time to realise i also needed to use recursion for this, and not just for retrieving the depth.
After this was solved, the rest of the implementation was done fairly quickly.
