= Part 2 : Graphs + Containers

== Research
There are multiple approaches to create an graph, adjacency matrix and adjacency list.
I settled on creating the graph with the help of the adjacency matrix.
An adjacency matrix can be seen as a table in which each connection between node x and y is defined by an given value.
This value is based on if there is an connection. 
When there is an connection, the value in the adjacency matrix is 1, otherwise it is 0.

To find the shortest path from the first node to the last node, there is made use of the Dijkstra algorithm.
This algorithm will be further discussed in the header Algorithm.

== Design
=== Adjacency matrix
To create the adjacency matrix, there is made use of an two dimensional array. 
Since an array cannot be uninitialized at compile time, the array is created during runtime.
This results in having to 'create' a "new int[x]" for each node and later on before running the next test, having to delete the allocated memory.

=== Algorithm
The used algorithm is based on the given algorithm as described on the following website; 
https://www.geeksforgeeks.org/dijkstras-shortest-path-algorithm-greedy-algo-7/ . 
A few adjustments had to be made to make it compatible with the code of my adjacency matrix and the compiler.
For example, as the seen in their algorithm, they use an hardcoded size for any new arrays. 
This means when having a different amount of nodes will throw more onto the stack then is actually possible.
To solve this, these arrays would be created during runtime, therefor the space for the array is allocated during runtime and freed after using them.
Another thing that has been adjusted is leaving out to find the distance from the source nodes to every other nodes, since this takes up unnecessary time.
To go into more detail about the algorithm itself, the algorithm makes use of the Breadth First Search.
It will take the source nodes and travel trough its connected nodes until the largest node is found, the found distance is returned.

== Reflection
Looking back at this part of the assignment, it has been a real struggle to get the right implementation.
Each time i would run into a new problem, which was difficult to solve.
The main problem was misreading the assignment, i scanned over it and missed some important parts of what had to be done.
Looking at the coding itself, most of the problems occurred with figuring out with being a bit sloppy with initializing variables and reusing variables names.
Lastly I struggled a lot with getting creating an 2D array during runtime.
When certain aspects clicked on why it wasn't working, it was an too hard to find the solution to the problem.
