= Client Meeting 16-03-2026

== Brussels Trip
n 7th of April there is a trip planned to Brussels, to get a tour within the european parliament. 
If there is anyone who would like to join, we should get in contact with Herm.

Prior to the trip, there will be a meeting with Herm to discuss questions we could be asking, but also to be more prepared for the visit and tour.

== Fitphone itself
Fitphone is a lifestyle and health project.
The main goal is to raise more awerness and possible 'intervations' regarding to the negative effects of social media on mental health.

There are various aspects that can be negatively impacted by social media and general phone usage.
The main aspects are the mental and physical health.
Example for mental health are the impact on sleep, the impact on self-esteem and emotions which are less understood and observed.
Example for physical health are the impact on posture, the impact on eyesight and the impact on physical activity.

For mote information on the various themes, it is suggested to take a look at the Fitphone website.

== Client's Idea
Herm's idea is to use AI to analyse data regarding to past and current running law suits related to social media and what it is about.
This can be used as an educative tool for integration within the app.
To make the people more aware of the potential dark and downsides of social media, how it can be misused.
Herm will take initiative to find the data and data sets regarding to this.

== The Project Proposal
It is agreed upon to have our idea to be leading for the project. Herm would like to see his idea to be incorporated within the project, but it is not a requirement.

As a side note, the app is not set in stone. It is flexible and does not necesarry have to be a phone app. This can be adapted based upon the project progress.
