[env:esp32_com3]
platform = espressif32
board = esp32dev
framework = arduino
upload_port = COM3
monitor_port = COM3
monitor_speed = 115200
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -D DEVICE_ID=1
    -D DEVICE_NAME=\"ESP32_COM3\"
    -D PLANT_LABEL=\"Aglaonema\"
    -D WIFI_SSID=\"vRijswijk\"
    -D WIFI_PASSWORD='"KvR1964w!%%"'
    -D MQTT_HOST=\"e5d9dbc64ffd42b4848c9940b62bf7a6.s1.eu.hivemq.cloud\"
    -D MQTT_PORT=8883
    -D MQTT_USERNAME=\"cstijlaart\"
    -D MQTT_PASSWORD=\"Mq!2000!cs\"
    -D MQTT_TOPIC_PREFIX=\"phm\"
    -D POF02_ENABLE_TINYML_TFLM=1
    -D MQTT_CLIENT_PREFIX=\"esp32\"

lib_deps =
    eloquentarduino/EloquentTinyML
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
    knolleary/PubSubClient

[env:esp32_com4]
platform = espressif32
board = esp32dev
framework = arduino
upload_port = COM4
monitor_port = COM4
monitor_speed = 115200
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -D DEVICE_ID=2
    -D DEVICE_NAME=\"ESP32_COM4\"
    -D PLANT_LABEL=\"Prayer-Plant\"
    -D WIFI_SSID=\"vRijswijk\"
    -D WIFI_PASSWORD='"KvR1964w!%%"'
    -D MQTT_HOST=\"e5d9dbc64ffd42b4848c9940b62bf7a6.s1.eu.hivemq.cloud\"
    -D MQTT_PORT=8883
    -D MQTT_USERNAME=\"cstijlaart\"
    -D MQTT_PASSWORD=\"Mq!2000!cs\"
    -D MQTT_TOPIC_PREFIX=\"phm\"
    -D POF02_ENABLE_TINYML_TFLM=1
    -D MQTT_CLIENT_PREFIX=\"esp32\"

lib_deps =
    eloquentarduino/EloquentTinyML
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
    knolleary/PubSubClient
